<?php

namespace App\Http\Controllers\Payroll;

use App\Support\ForceMode;
use App\Http\Controllers\Controller;
use App\Models\PayrollAdvance;
use App\Models\SalaryProcessing;
use App\Support\PayrollContext;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class PayrollAdvanceController extends Controller
{
    public function index()
    {
        $company = PayrollContext::currentOrFail();

        $advances = PayrollAdvance::with('employee')
            ->where('payroll_company_id', $company->id)
            // Latest advance first; the ID keeps same-day rows in a stable order
            ->orderByDesc('advance_date')->orderByDesc('id')->get();

        return view('payroll.pages.advance', [
            'company' => $company,
            'advances' => $advances,
            'activeEmployees' => \App\Models\Employee::where('payroll_company_id', $company->id)
                ->where('is_active', true)->orderBy('name')->get(),
            'summary' => [
                'issued' => (float) $advances->sum('amount'),
                'recovered' => (float) $advances->sum('recovered_amount'),
                'outstanding' => (float) $advances->sum(fn ($a) => $a->outstanding()),
                'open' => $advances->where('is_settled', false)->count(),
            ],
        ]);
    }

    private function rules(): array
    {
        return [
            'employee_id' => ['required', \App\Support\PayrollScope::belongsToCompany('employees')],
            'advance_date' => ['required', 'date', 'before_or_equal:now'],
            'amount' => ['required', 'numeric', 'gt:0'],
            'deduction_type' => ['required', Rule::in(['One Time', 'Monthly'])],
            // A monthly recovery is meaningless without an instalment: it would
            // never clear. One Time ignores it and takes the whole amount.
            'deduction_amount' => [
                'nullable', 'numeric', 'min:0', 'required_if:deduction_type,Monthly',
                function ($attribute, $value, $fail) {
                    if (request('deduction_type') === 'Monthly' && (float) $value <= 0) {
                        $fail('A monthly recovery needs an instalment greater than zero.');
                    }
                },
            ],
            'remarks' => ['nullable', 'string'],
        ];
    }

    private function messages(): array
    {
        return [
            'amount.gt' => 'Advance amount must be greater than zero.',
            'advance_date.before_or_equal' => 'Advance date cannot be in the future.',
        ];
    }

    /**
     * Blocks edits once the period the advance belongs to has been processed.
     */
    private function periodProcessed(PayrollAdvance $advance): bool
    {
        $date = Carbon::parse($advance->advance_date);

        return SalaryProcessing::where('payroll_company_id', $advance->payroll_company_id)
            ->where('employee_id', $advance->employee_id)
            ->where('year', $date->year)
            ->where('month', $date->month)
            ->exists();
    }

    public function store(Request $request)
    {
        $company = PayrollContext::currentOrFail();

        $data = $request->validate($this->rules(), $this->messages());
        $data['payroll_company_id'] = $company->id;
        $data['created_by'] = Auth::id();

        if ($data['deduction_type'] === 'One Time') {
            $data['deduction_amount'] = $data['amount'];
        }

        PayrollAdvance::create($data);

        return back()->with('success', 'Advance recorded.');
    }

    public function update(Request $request, PayrollAdvance $advance)
    {
        \App\Support\PayrollScope::ensure($advance);

        if (ForceMode::locked(! Auth::user()->isAdmin(), 'Only Admin users can update advance records')) {
            return back()->with('error', 'Only Admin users can update advance records.');
        }

        if (ForceMode::locked($advance->is_carry_forward, 'Carry-forward advances are generated by Salary Processing and')) {
            return back()->with('error', 'Carry-forward advances are generated by Salary Processing and cannot be edited.');
        }

        if (ForceMode::locked($this->periodProcessed($advance), 'Salary Processing is already completed for this period,')) {
            return back()->with('error', 'Salary Processing is already completed for this period, so this advance cannot be changed.');
        }

        $data = $request->validate($this->rules(), $this->messages());

        if ($data['deduction_type'] === 'One Time') {
            $data['deduction_amount'] = $data['amount'];
        }

        $advance->update($data);

        return back()->with('success', 'Advance updated.');
    }

    public function destroy(PayrollAdvance $advance)
    {
        \App\Support\PayrollScope::ensure($advance);

        if (ForceMode::locked(! Auth::user()->isAdmin(), 'Only Admin users can delete advance records')) {
            return back()->with('error', 'Only Admin users can delete advance records.');
        }

        if (ForceMode::locked($advance->is_carry_forward, 'Carry-forward advances are generated by Salary Processing and')) {
            return back()->with('error', 'Carry-forward advances are generated by Salary Processing and cannot be deleted.');
        }

        if (ForceMode::locked($this->periodProcessed($advance), 'Salary Processing is already completed for this period,')) {
            return back()->with('error', 'Salary Processing is already completed for this period, so this advance cannot be deleted.');
        }

        $advance->delete();

        return back()->with('success', 'Advance deleted.');
    }

    public function view(PayrollAdvance $advance)
    {
        \App\Support\PayrollScope::ensure($advance);

        $advance->load('employee', 'company', 'creator');

        return \App\Support\PayrollPdf::make('payroll.pdf.advance', compact('advance'))
            ->stream('advance-'.$advance->id.'.pdf');
    }
}
