<?php

namespace App\Http\Controllers\Payroll;

use App\Support\ForceMode;
use App\Http\Controllers\Controller;
use App\Models\PayrollAdvance;
use App\Models\SalaryProcessing;
use App\Support\PayrollContext;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class PayrollAdvanceController extends Controller
{
    private function rules(): array
    {
        return [
            'employee_id' => ['required', 'exists:employees,id'],
            'advance_date' => ['required', 'date', 'before_or_equal:now'],
            'amount' => ['required', 'numeric', 'gt:0'],
            'deduction_type' => ['required', Rule::in(['One Time', 'Monthly'])],
            'deduction_amount' => ['nullable', 'numeric', 'min:0'],
            'remarks' => ['nullable', 'string'],
        ];
    }

    private function messages(): array
    {
        return [
            'amount.gt' => 'Advance amount must be greater than zero.',
            'advance_date.before_or_equal' => 'Advance date cannot be in the future.',
        ];
    }

    /**
     * Blocks edits once the period the advance belongs to has been processed.
     */
    private function periodProcessed(PayrollAdvance $advance): bool
    {
        $date = Carbon::parse($advance->advance_date);

        return SalaryProcessing::where('payroll_company_id', $advance->payroll_company_id)
            ->where('employee_id', $advance->employee_id)
            ->where('year', $date->year)
            ->where('month', $date->month)
            ->exists();
    }

    public function store(Request $request)
    {
        $company = PayrollContext::currentOrFail();

        $data = $request->validate($this->rules(), $this->messages());
        $data['payroll_company_id'] = $company->id;
        $data['created_by'] = Auth::id();

        if ($data['deduction_type'] === 'One Time') {
            $data['deduction_amount'] = $data['amount'];
        }

        PayrollAdvance::create($data);

        return back()->with('success', 'Advance recorded.');
    }

    public function update(Request $request, PayrollAdvance $advance)
    {
        if (ForceMode::locked(! Auth::user()->isAdmin(), 'Only Admin users can update advance records')) {
            return back()->with('error', 'Only Admin users can update advance records.');
        }

        if (ForceMode::locked($advance->is_carry_forward, 'Carry-forward advances are generated by Salary Processing and')) {
            return back()->with('error', 'Carry-forward advances are generated by Salary Processing and cannot be edited.');
        }

        if (ForceMode::locked($this->periodProcessed($advance), 'Salary Processing is already completed for this period,')) {
            return back()->with('error', 'Salary Processing is already completed for this period, so this advance cannot be changed.');
        }

        $data = $request->validate($this->rules(), $this->messages());

        if ($data['deduction_type'] === 'One Time') {
            $data['deduction_amount'] = $data['amount'];
        }

        $advance->update($data);

        return back()->with('success', 'Advance updated.');
    }

    public function destroy(PayrollAdvance $advance)
    {
        if (ForceMode::locked(! Auth::user()->isAdmin(), 'Only Admin users can delete advance records')) {
            return back()->with('error', 'Only Admin users can delete advance records.');
        }

        if (ForceMode::locked($advance->is_carry_forward, 'Carry-forward advances are generated by Salary Processing and')) {
            return back()->with('error', 'Carry-forward advances are generated by Salary Processing and cannot be deleted.');
        }

        if (ForceMode::locked($this->periodProcessed($advance), 'Salary Processing is already completed for this period,')) {
            return back()->with('error', 'Salary Processing is already completed for this period, so this advance cannot be deleted.');
        }

        $advance->delete();

        return back()->with('success', 'Advance deleted.');
    }

    public function view(PayrollAdvance $advance)
    {
        $advance->load('employee', 'company', 'creator');

        return Pdf::loadView('payroll.pdf.advance', compact('advance'))
            ->stream('advance-'.$advance->id.'.pdf');
    }
}
